version: '3'

services:
  discord-bot:
    image: lncrawl
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    command: python -m lncrawl --bot discord --shard-id 0 --shard-count 1 --suppress
    environment:
      CLOUD_DRIVE: "ANONFILES"
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      DISCORD_SIGNAL_CHAR: "${DISCORD_SIGNAL_CHAR}"
      DISCORD_DISABLE_SEARCH: "${DISCORD_DISABLE_SEARCH}"

  telegram-bot:
    image: lncrawl
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    command: python -m lncrawl --bot telegram
    environment:
      CLOUD_DRIVE: "ANONFILES"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
 
