name: Generate source index

on:
  push:
    branches:
      - dev
    paths:
      - "sources/**"
      - "!sources/_index.json"
      - "scripts/index_gen.py"
      - "lncrawl/VERSION"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  index_gen:
    if: github.repository == 'dipu-bd/lightnovel-crawler'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements-app.txt

      - name: Generate index
        run: python ./scripts/index_gen.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate source index
